### ISSUE TITLE
Unable to use gpt-neox-20b model 

### ISSUE THREAD

**Issue by rachelxx03** [anarchy-ai/LLM-VM#240]
this is the error i got when i run tried gpt-neox-20b
Project Root: /lustre06/project/6084228/gpt-neo-1.3b/lib/python3.11/site-packages/llm_vm
You are using a model of type gpt_neox to instantiate a model of type gpt_neo. This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "/lustre06/project/6084228/PubMed/gpt-neox-20b/newli.py", line 5, in <module>
    client = Client(big_model = 'neo', big_model_config={'model_uri':'EleutherAI/gpt-neox-20b'})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6084228/gpt-neo-1.3b/lib/python3.11/site-packages/llm_vm/client.py", line 50, in __init__
    self.teacher = load_model_closure(big_model)(**big_model_config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6084228/gpt-neo-1.3b/lib/python3.11/site-packages/llm_vm/onsite_llm.py", line 83, in __init__
    self.model=self.model_loader(**model_kw_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6084228/gpt-neo-1.3b/lib/python3.11/site-packages/llm_vm/onsite_llm.py", line 277, in model_loader
    return GPTNeoForCausalLM.from_pretrained(self.model_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6084228/gpt-neo-1.3b/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2700, infrom_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6084228/gpt-neo-1.3b/lib/python3.11/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 670, in __init__
    self.transformer = GPTNeoModel(config)
                       ^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6084228/gpt-neo-1.3b/lib/python3.11/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 485, in __init__
    self.h = nn.ModuleList([GPTNeoBlock(config, layer_id=i) for i in range(config.num_layers)])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6084228/gpt-neo-1.3b/lib/python3.11/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 485, in <listcomp>
    self.h = nn.ModuleList([GPTNeoBlock(config, layer_id=i) for i in range(config.num_layers)])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6084228/gpt-neo-1.3b/lib/python3.11/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 313, in __init__
    self.attn = GPTNeoAttention(config, layer_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6084228/gpt-neo-1.3b/lib/python3.11/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 261, in __init__
    self.attention_type = self.attention_layers[layer_id]
                          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range  . I am using the code in our documentation

**Comment by mmirman** [comment]
This is on here?  https://www.scinethpc.ca/niagara/ 

Can you give us an output of system-config?

**Comment by VictorOdede** [comment]
Hey @rachelxx03, did you manage to run the models?

**Comment by rachelxx03** [comment]
@VictorOdede  i got this error     class Quantized_Llama(Base_Onsite_LLM):
                          ^^^^^^^^^^^^^^^
NameError: name 'Base_Onsite_LLM' is not defined. Did you mean: 'BaseOnsiteLLM'?

**Comment by VictorOdede** [comment]
> @VictorOdede i got this error class Quantized_Llama(Base_Onsite_LLM): ^^^^^^^^^^^^^^^ NameError: name 'Base_Onsite_LLM' is not defined. Did you mean: 'BaseOnsiteLLM'?

Let me look into this, will get back to you by tomorrow

**Comment by VictorOdede** [comment]
> @VictorOdede i got this error class Quantized_Llama(Base_Onsite_LLM): ^^^^^^^^^^^^^^^ NameError: name 'Base_Onsite_LLM' is not defined. Did you mean: 'BaseOnsiteLLM'?

Kindly share the code you're trying to run

**Comment by VictorOdede** [comment]
Hey @rachelxx03 I've fixed the error you mentioned above. Kindly pull in the latest changes to your repo and let me know if it works.
