### ISSUE TITLE
Docker run failed

### ISSUE THREAD

**Issue by LYZJU2019** [anarchy-ai/LLM-VM#283]
I was trying to run LLM-VM (commit id: [5395194](https://github.com/anarchy-ai/LLM-VM/commit/53951944736cd7c1f3661c1ee5d0845af6984679)) in docker containers. I executed the following steps:

#### Step 1: Build docker image

```sh
docker build --tag "llm-vm" .
```

#### Step 2: Start the container

```sh
docker run -d "llm-vm"
```

However, my container failed to start, the error message is shown below:

```txt
2023-09-18 17:07:02 Traceback (most recent call last):
2023-09-18 17:07:02   File "/app/src/llm_vm/server/main.py", line 13, in <module>
2023-09-18 17:07:02     import llm_vm.server.routes as routes
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/llm_vm/server/routes.py", line 6, in <module>
2023-09-18 17:07:02     from llm_vm.agents.REBEL import agent
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/llm_vm/agents/REBEL/agent.py", line 32, in <module>
2023-09-18 17:07:02     import spacy
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/spacy/__init__.py", line 6, in <module>
2023-09-18 17:07:02     from .errors import setup_default_warnings
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/spacy/errors.py", line 3, in <module>
2023-09-18 17:07:02     from .compat import Literal
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/spacy/compat.py", line 4, in <module>
2023-09-18 17:07:02     from thinc.util import copy_array
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/thinc/__init__.py", line 5, in <module>
2023-09-18 17:07:02     from .config import registry
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/thinc/config.py", line 5, in <module>
2023-09-18 17:07:02     from .types import Decorator
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/thinc/types.py", line 25, in <module>
2023-09-18 17:07:02     from .compat import cupy, has_cupy
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/thinc/compat.py", line 30, in <module>
2023-09-18 17:07:02     import torch
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/torch/__init__.py", line 1239, in <module>
2023-09-18 17:07:02     from torch import onnx as onnx
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/torch/onnx/__init__.py", line 12, in <module>
2023-09-18 17:07:02     from . import (  # usort:skip. Keep the order instead of sorting lexicographically
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/torch/onnx/symbolic_caffe2.py", line 4, in <module>
2023-09-18 17:07:02     from torch.onnx import symbolic_helper, symbolic_opset9 as opset9
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/torch/onnx/symbolic_helper.py", line 611, in <module>
2023-09-18 17:07:02     def _onnx_unsupported(op_name: str, value: Optional[_C.Value] = None) -> NoReturn:
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_decor/decorcache.py", line 77, in beartype
2023-09-18 17:07:02     return beartype_object(obj, conf)
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_decor/decorcore.py", line 98, in beartype_object
2023-09-18 17:07:02     _beartype_object_fatal(obj, conf=conf, **kwargs)
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_decor/decorcore.py", line 147, in _beartype_object_fatal
2023-09-18 17:07:02     beartype_nontype(obj, **kwargs)  # type: ignore[return-value]
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_decor/_decormore.py", line 178, in beartype_nontype
2023-09-18 17:07:02     return beartype_func(obj, **kwargs)  # type: ignore[return-value]
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_decor/_decormore.py", line 242, in beartype_func
2023-09-18 17:07:02     func_wrapper_code = generate_code(bear_call)
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_decor/wrap/wrapmain.py", line 187, in generate_code
2023-09-18 17:07:02     code_check_return = _code_check_return(bear_call)
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_decor/wrap/wrapmain.py", line 669, in _code_check_return
2023-09-18 17:07:02     reraise_exception_placeholder(
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_util/error/utilerror.py", line 214, in reraise_exception_placeholder
2023-09-18 17:07:02     raise exception.with_traceback(exception.__traceback__)
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_decor/wrap/wrapmain.py", line 618, in _code_check_return
2023-09-18 17:07:02     ) = make_func_wrapper_code(hint_sane, bear_call.conf, cls_stack)  # type: ignore[assignment]
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_util/cache/utilcachecall.py", line 259, in _callable_cached
2023-09-18 17:07:02     raise exception
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_util/cache/utilcachecall.py", line 251, in _callable_cached
2023-09-18 17:07:02     return_value = args_flat_to_return_value[args_flat] = func(
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_decor/wrap/_wrapcode.py", line 86, in make_func_wrapper_code
2023-09-18 17:07:02     ) = make_check_expr(hint, conf, cls_stack)
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_util/cache/utilcachecall.py", line 259, in _callable_cached
2023-09-18 17:07:02     raise exception
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_util/cache/utilcachecall.py", line 251, in _callable_cached
2023-09-18 17:07:02     return_value = args_flat_to_return_value[args_flat] = func(
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_check/code/codemake.py", line 706, in make_check_expr
2023-09-18 17:07:02     die_if_hint_pep_unsupported(
2023-09-18 17:07:02   File "/usr/local/lib/python3.10/site-packages/beartype/_util/hint/pep/utilpeptest.py", line 205, in die_if_hint_pep_unsupported
2023-09-18 17:07:02     raise BeartypeDecorHintPep484Exception(
2023-09-18 17:07:02 beartype.roar.BeartypeDecorHintPep484Exception: Function torch.onnx.symbolic_helper._onnx_unsupported() return PEP 484 type hint "typing.NoReturn" invalid in this type hint context (i.e., "typing.NoReturn" valid only as non-nested return annotation).
```

Did I miss some steps in the setup stage, or it's a current issue to be fixed?

**Comment by LYZJU2019** [comment]
I've tried the pull request [282](https://github.com/anarchy-ai/LLM-VM/pull/282) and it's now working!
